[package]
name = "compression"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.24"
eframe = "0.27.0"
rfd = "0.14.1"
dirs = "5.0.1"
tar = "0.4"
log = "0.4"
env_logger = "0.11.3"
image = "0.25.1"
winit = "0.30.0"